### ISSUE TITLE
mjolnir.tiling is very slow

### ISSUE THREAD

**Issue by amrav** [nathankot/mjolnir.tiling#13]
Hi. I'm trying to use mjolnir.tiling on OS X 10.10.2 with Lua 5.2.3 and Mjolnir 0.4.3. Cycling through layouts takes a long time, around 5s every time I cycle. I've recorded a [screencast](http://tinypic.com/r/213k5rs/8) - this is in real time, and I'm cycling as soon as a new layout shows.  Here's my config:

```lua
local application = require "mjolnir.application"
local hotkey = require "mjolnir.hotkey"
local window = require "mjolnir.window"
local fnutils = require "mjolnir.fnutils"
local tiling = require "mjolnir.tiling"

local hyper = {"ctrl", "alt", "cmd"}

hotkey.bind(hyper, "c", function() tiling.cyclelayout() end)
hotkey.bind(hyper, "j", function() tiling.cycle(1) end)
hotkey.bind(hyper, "k", function() tiling.cycle(-1) end)
hotkey.bind(hyper, "space", function() tiling.promote() end)
``` 

Is this behaviour expected? Why could this be happening?

**Comment by nathankot** [comment]
Hey @amrav, that looks quite unusable! Here's a recording of mine: 
http://cl.ly/ZknE
(there's a missing tile due to quicktime screen recorder)

What's your load average? mine during the recording:

```
$ uptime
 0:34  up 12 days, 12:25, 1 user, load averages: 2.07 2.35 2.32
```

**Comment by amrav** [comment]
Yeah, that seems much more expected. My load average is quite low:
```
17:34  up 6 days,  1:31, 1 user, load averages: 1.95 1.88 1.90
```

It's equally slow when I try to cycle through windows. However, it's not happening when I use this:
```
hotkey.bind(hyper, "D", function()
  local win = window.focusedwindow()
  local f = win:frame()
  f.x = f.x + 10
  win:setframe(f)
end)
```
which makes me suspect it's not a mjolnir-wide issue.

**Comment by nathankot** [comment]
hey,

Are you on the latest version of `mjolnir.tiling`? I do get bursts of
unresponsiveness occasionally when there are too many windows, and for some
particular layouts - is the slowness in random or just consistently?
ᐧ

**Comment by amrav** [comment]
I'm on mjolnir.tiling 0.3.0-1. The slowness is consistent, and independent of the number of windows open. Even with two windows - Chrome and iTunes, it's just as slow. I've also tried shutting these applications and trying with completely different applications - same result. Is there any way to see a log, or profile mjolnir, to find out where the slowness is?

**Comment by nathankot** [comment]
@amrav I just pushed a benchmarking branch `benchmarking`, for me there is a bottleneck at `getspace()` but you can get some timings with the following:

```sh
git clone https://github.com/nathankot/mjolnir.tiling
cd mjolnir.tiling
git checkout benchmarking
luarocks install luasocket # need this for benchmark timings
luarocks make
```

and then reload your mjolnir, do some layout cycles and copy and paste the output in mjolnir console please ^^

**Comment by amrav** [comment]
Thanks for the benchmarking code! I have a major bottleneck at `getspace()`, ~6s. I have two Spaces open, one is a fullscreen terminal. I also have the Dashboard activated. The problem persists even if I remove everything and only have one Space.

mjolnir console output: http://pastebin.com/i1q1zhYE

**Comment by amrav** [comment]
Something really weird is happening. I tried to pinpoint the exact source of the slowness, and I eventually got to this:

```lua
function getspace()
  local start = socket.gettime()
  x = socket.gettime()
  local windows = fnutils.filter(window.visiblewindows(), iswindowincluded)
  y = socket.gettime()
  local end_ = socket.gettime()

  print(string.format("fnutils.filter time: %.6f\n", y - x))
  print(string.format("bottleneck: %.6f\n", end_ - start))
```
where `bottleneck` is the new timing variable I've added. Here are my results (some lines removed for brevity):

```
fnutils.filter time: 0.000003
bottleneck: 6.049716
getspace time: 6.050608
layoutcycle time: 0.000001
apply time: 0.301619
```

Aren't `bottleneck` and `fnutils.filter time` measuring the same thing?

**Comment by Ezmyrelda** [comment]
I can also report the same behavior.

**Comment by amrav** [comment]
Okay, the above issue is caused by not using `local` for `x` and `y`. This modifies `x` and `y` from the caller functions, and gives us wrong timing results.

I then tried this test:
```lua
  local x = socket.gettime()
  local vis_start = socket.gettime()
  local visibleWindows = window.visiblewindows()
  local vis_end = socket.gettime()
  print(string.format("window.visiblewindows(): %.6f\n", vis_end - vis_start))
  local windows = fnutils.filter(visibleWindows, iswindowincluded)
  local y = socket.gettime()
  print(string.format("fnutils.filter time: %.6f\n", y - x))
```

and got:

```
window.visiblewindows(): 6.045786
fnutils.filter time: 6.074302
getspace time: 6.075190
```

So the bottleneck is in `window.visiblewindows()`.

**Comment by amrav** [comment]
`application.allwindows()`, called by `window.visiblewindows()`, was taking most of the time on just one application. Upon investigation, this turned out to be NoMachine. I'm not sure why this was happening, but uninstalling NoMachine solved the issue for me.

**Comment by nathankot** [comment]
@amrav nice :+1: sorry about the misleading benchmarking code! I'll push a fixed version to `benchmarking`

@Ezmyrelda could you please [follow the same steps](https://github.com/nathankot/mjolnir.tiling/issues/13#issuecomment-74150488) to see if you have the same source of slowness?

**Comment by Ezmyrelda** [comment]
win:screen time: 0.000480

win:isstandard time: 0.000074

#win:title time: 0.000067

excluded[win time: 0.000001

win:screen time: 0.000426

win:isstandard time: 0.000101

#win:title time: 0.000131

excluded[win time: 0.000000

win:screen time: 0.000272

win:isstandard time: 0.000029

#win:title time: 0.000041

excluded[win time: 0.000001

fnutils.filter time: 8.020923

fnutils.each time: 0.000002

table.sort time: 0.000001

space creation time: 0.000005

syncwindows time: 0.000145

getspace time: 8.022580

layoutcycle time: 0.000006

apply time: 0.580412

win:screen time: 0.000465

win:isstandard time: 0.000109

#win:title time: 0.000098

excluded[win time: 0.000001

win:screen time: 0.000450

win:isstandard time: 0.000087

#win:title time: 0.000085

excluded[win time: 0.000001

win:screen time: 0.000280

win:isstandard time: 0.000028

#win:title time: 0.000040

excluded[win time: 0.000001

fnutils.filter time: 6.041822

fnutils.each time: 0.000010

table.sort time: 0.000001

syncwindows time: 0.000238

getspace time: 6.044648

layoutcycle time: 0.000002

apply time: 0.166075

**Comment by nathankot** [comment]
@Ezmyrelda looks like you've got the same problem as @amrav, @amrav how did you figure out which application was causing the issue? is it a trial and error thing?

might be worthwhile opening a ticket at [mjolnir](https://github.com/sdegutis/mjolnir) but i'm afraid that repo hasn't been very active...

**Comment by nathankot** [comment]
@Ezmyrelda please try the `benchmarking` branch again, @amrav has kindly added some slow-application detection code :smile:

**Comment by Ezmyrelda** [comment]
@nathankot Yes, it's slightly better.. There is still a several beat pause before anything happens though.

**Comment by nathankot** [comment]
@Ezmyrelda which was the offending application?

**Comment by Ezmyrelda** [comment]
@nathankot I'm not sure what you mean.. It happens with no out of the ordinary apps open and trying to switch layouts with only terminal and finder windows open.

**Comment by nathankot** [comment]
@Ezmyrelda ahh okay so the problem fixed itself? The `benchmarking` bench didn't make any performance improvements, just profiling to see how long it takes to call `getwindows()` on each application so if you have a look at your Mjolnir Console after a few layout switches it should tell you where the bottleneck is :smile:

**Comment by Ezmyrelda** [comment]
Well, no.. I guess there is a miscommunication then.. I said it was a little better.. So it was probably a fluke.. The problem was not actually resolved and continues to happen with only finder windows open.. So.. I guess.. finder is the bottleneck?

**Comment by nathankot** [comment]
@Ezmyrelda hmmm i see, how slow is it? if ~1s then it could be normal

**Comment by Ezmyrelda** [comment]
@nathankot 2-3 seconds.

**Comment by mbernath** [comment]
I can confirm the same problem. I also experience a 2-3 seconds duration of window.visiblewindows() that occurs at random (about 1 in 10 times).

Has anybody found a solution yet for this issue?

**Comment by nathankot** [comment]
The relevant lines would be: https://github.com/sdegutis/mjolnir/blob/c246c92eebdc7be4d9eaa760cbb837c4ef890209/mods/application/window.lua#L25-L27 and https://github.com/sdegutis/mjolnir/blob/8fe9ef322dc2d0e2f8a27601e90b14ed5711bcde/mods/application/application.m#L82-L104 if someone wants to look into it =D

**Comment by mbernath** [comment]
@nathankot Thanks! I had a quick look and it appears that ```application_allwindows()``` is causing the delay for some (but random) applications. At least it is not ```application.runningapplications()```.

My quick&dirty test code was:

    local t1, t2, diff
    local apps

    for i=0,20,1 do
      apps = application.runningapplications()
      for k,v in pairs(apps) do
        t1 = os.time()
        local win = application.allwindows(v)
        t2 = os.time()
        diff = os.difftime(t2,t1)
        if diff > 0.5 then
          print("Long running allwindows call", diff, v:pid())
        end
      end
    end
    print "completed"

I manually checked the pids and every run other pids appeared. So it is likely not a problem with some special applications.

**Comment by skrobul** [comment]
Can confirm same issue. Posted benchmarking results at https://gist.github.com/skrobul/3e0f2f72afde5d0cfc70  - getSpace is about 6 seconds.

**Comment by skrobul** [comment]
I think I found a workaround for now. I went to `Settings -> Mission Control` and unchecked `Displays have separate Spaces` and the delay seems  to be gone. It could be result of starting fresh session though...

**Comment by nathankot** [comment]
Sorry for the slow reply, I've been moving into a new place so things have taken a while!

@mbernath that's good insight, so it's not a application-specific thing, wonder if @skrobul 's solution above makes things better?

**Comment by skrobul** [comment]
@nathankot yeah, it removed delay for me completely.

**Comment by mbernath** [comment]
@nathankot I've tried @skrobul 's solution, but the workaround did not work for me. Tested with 1 external monitor connected and without. I'm running Yosemite 10.10.3.

**Comment by nathankot** [comment]
thanks for the update @mbernath , i'll take a proper look into this over the weekend - although I haven't run into this issue myself i'll try to speed as many things up as I can, will probably involve a patch to mjolnir itself by the looks of it tho

**Comment by nathankot** [comment]
@mbernath I've forked mjolnir and made a benchmarking branch: https://github.com/nathankot/mjolnir/tree/benchmark-allwindows-slowness

Can you use it to try and pinpoint the source of slowness? I can't seem to reproduce it, my diff is here: https://github.com/nathankot/mjolnir/commit/b58479d0671b6d954a08a5ff23ebd4d78ad4253c

To get the log output, you'll have to run mjolnir from xcode so:

```sh
git clone https://github.com/nathankot/mjolnir.git
cd mjolnir
git checkout benchmark-allwindows-slowness
open Mjolnir.xcodeproj
# Press run in xcode and keep it running
# Then make changes to mods/application
# You'll need to `luarocks make` the application module in order to reflect changes like so:
cd mods/application
luarocks make mjolnir.application-0.3-1.rockspec
```

**Comment by mbernath** [comment]
@nathankot Great! I've just run the benchmarks with many windows open and also only with few.

For each run I can pinpoint the cause of the slowness to one program (see bold line below). But I'm not sure, if it is always the same app. Sorry for my ignorance of Objective C, but how could I also log the pid or app name for each measurement? Then I could determine if it is really always the same program running or if the delay just occurs at random...

Sample benchmarks (many programs & windows open):

2015-05-30 17:31:52.926 Mjolnir[89886:13406834] -0.00029200315475463867
2015-05-30 17:31:52.927 Mjolnir[89886:13406834] -0.00037699937820434570
2015-05-30 17:31:52.927 Mjolnir[89886:13406834] -0.00005298852920532227
2015-05-30 17:31:52.928 Mjolnir[89886:13406834] -0.00111097097396850586
2015-05-30 17:31:52.928 Mjolnir[89886:13406834] -0.00015604496002197266
2015-05-30 17:31:52.929 Mjolnir[89886:13406834] -0.00028496980667114258
2015-05-30 17:31:52.929 Mjolnir[89886:13406834] -0.00033098459243774414
2015-05-30 17:31:52.930 Mjolnir[89886:13406834] -0.00014698505401611328
2015-05-30 17:31:52.930 Mjolnir[89886:13406834] -0.00027102231979370117
2015-05-30 17:31:52.930 Mjolnir[89886:13406834] -0.00025600194931030273
2015-05-30 17:31:52.931 Mjolnir[89886:13406834] -0.00011897087097167969
2015-05-30 17:31:52.931 Mjolnir[89886:13406834] -0.00028699636459350586
2015-05-30 17:31:52.931 Mjolnir[89886:13406834] -0.00023400783538818359
2015-05-30 17:31:52.932 Mjolnir[89886:13406834] -0.00028800964355468750
2015-05-30 17:31:52.932 Mjolnir[89886:13406834] -0.00030398368835449219
2015-05-30 17:31:52.932 Mjolnir[89886:13406834] -0.00021398067474365234
2015-05-30 17:31:52.933 Mjolnir[89886:13406834] -0.00021797418594360352
2015-05-30 17:31:52.943 Mjolnir[89886:13406834] -0.00035703182220458984
2015-05-30 17:31:52.943 Mjolnir[89886:13406834] -0.00036400556564331055
2015-05-30 17:31:52.944 Mjolnir[89886:13406834] -0.00037997961044311523
2015-05-30 17:31:52.944 Mjolnir[89886:13406834] -0.00035995244979858398
2015-05-30 17:31:52.945 Mjolnir[89886:13406834] -0.00010102987289428711
2015-05-30 17:31:52.945 Mjolnir[89886:13406834] -0.00044900178909301758
2015-05-30 17:31:52.946 Mjolnir[89886:13406834] -0.00026702880859375000
2015-05-30 17:31:52.946 Mjolnir[89886:13406834] -0.00024998188018798828
2015-05-30 17:31:52.946 Mjolnir[89886:13406834] -0.00042098760604858398
2015-05-30 17:31:52.947 Mjolnir[89886:13406834] -0.00016099214553833008
2015-05-30 17:31:52.947 Mjolnir[89886:13406834] -0.00015401840209960938
2015-05-30 17:31:52.947 Mjolnir[89886:13406834] -0.00012499094009399414
2015-05-30 17:31:52.947 Mjolnir[89886:13406834] -0.00011098384857177734
2015-05-30 17:31:52.948 Mjolnir[89886:13406834] -0.00014597177505493164
2015-05-30 17:31:52.948 Mjolnir[89886:13406834] -0.00013500452041625977
2015-05-30 17:31:52.948 Mjolnir[89886:13406834] -0.00012403726577758789
2015-05-30 17:31:52.949 Mjolnir[89886:13406834] -0.00011396408081054688
2015-05-30 17:31:52.949 Mjolnir[89886:13406834] -0.00012397766113281250
2015-05-30 17:31:52.949 Mjolnir[89886:13406834] -0.00012999773025512695
2015-05-30 17:31:52.950 Mjolnir[89886:13406834] -0.00089997053146362305
2015-05-30 17:31:52.950 Mjolnir[89886:13406834] -0.00027298927307128906
2015-05-30 17:31:52.951 Mjolnir[89886:13406834] -0.00015699863433837891
2015-05-30 17:31:52.951 Mjolnir[89886:13406834] -0.00038295984268188477
2015-05-30 17:31:52.952 Mjolnir[89886:13406834] -0.00013399124145507812
2015-05-30 17:31:52.952 Mjolnir[89886:13406834] -0.00041198730468750000
2015-05-30 17:31:52.953 Mjolnir[89886:13406834] -0.00033295154571533203
2015-05-30 17:31:52.953 Mjolnir[89886:13406834] -0.00033795833587646484
2015-05-30 17:31:52.953 Mjolnir[89886:13406834] -0.00024396181106567383
2015-05-30 17:31:52.954 Mjolnir[89886:13406834] -0.00034999847412109375
2015-05-30 17:31:52.954 Mjolnir[89886:13406834] -0.00050896406173706055
2015-05-30 17:31:52.955 Mjolnir[89886:13406834] -0.00023198127746582031
2015-05-30 17:31:52.955 Mjolnir[89886:13406834] -0.00011503696441650391
**2015-05-30 17:31:54.104 Mjolnir[89886:13406834] -1.14922297000885009766**
2015-05-30 17:31:54.106 Mjolnir[89886:13406834] -0.00126194953918457031
2015-05-30 17:31:54.106 Mjolnir[89886:13406834] -0.00010401010513305664
2015-05-30 17:31:54.106 Mjolnir[89886:13406834] -0.00029700994491577148
2015-05-30 17:31:54.107 Mjolnir[89886:13406834] -0.00022900104522705078
2015-05-30 17:31:54.107 Mjolnir[89886:13406834] -0.00018596649169921875
2015-05-30 17:31:54.107 Mjolnir[89886:13406834] -0.00023502111434936523
2015-05-30 17:31:54.109 Mjolnir[89886:13406834] -0.00110501050949096680
2015-05-30 17:31:54.109 Mjolnir[89886:13406834] -0.00017797946929931641
2015-05-30 17:31:54.109 Mjolnir[89886:13406834] -0.00030601024627685547
2015-05-30 17:31:54.110 Mjolnir[89886:13406834] -0.00046598911285400391
2015-05-30 17:31:54.110 Mjolnir[89886:13406834] -0.00015598535537719727
2015-05-30 17:31:54.111 Mjolnir[89886:13406834] -0.00045096874237060547
2015-05-30 17:31:54.111 Mjolnir[89886:13406834] -0.00033301115036010742
2015-05-30 17:31:54.112 Mjolnir[89886:13406834] -0.00015598535537719727
2015-05-30 17:31:54.112 Mjolnir[89886:13406834] -0.00026404857635498047
2015-05-30 17:31:54.112 Mjolnir[89886:13406834] -0.00024098157882690430
2015-05-30 17:31:54.113 Mjolnir[89886:13406834] -0.00024402141571044922
2015-05-30 17:31:54.113 Mjolnir[89886:13406834] -0.00017797946929931641
2015-05-30 17:31:54.113 Mjolnir[89886:13406834] -0.00034099817276000977
2015-05-30 17:31:54.114 Mjolnir[89886:13406834] -0.00035500526428222656
2015-05-30 17:31:54.114 Mjolnir[89886:13406834] -0.00035101175308227539
2015-05-30 17:31:54.115 Mjolnir[89886:13406834] -0.00014901161193847656
2015-05-30 17:31:54.115 Mjolnir[89886:13406834] -0.00013798475265502930
2015-05-30 17:31:54.115 Mjolnir[89886:13406834] -0.00010704994201660156
2015-05-30 17:31:54.116 Mjolnir[89886:13406834] -0.00045102834701538086
2015-05-30 17:31:54.116 Mjolnir[89886:13406834] -0.00014799833297729492
2015-05-30 17:31:54.117 Mjolnir[89886:13406834] -0.00064295530319213867
2015-05-30 17:31:54.117 Mjolnir[89886:13406834] -0.00014603137969970703
2015-05-30 17:31:54.117 Mjolnir[89886:13406834] -0.00012600421905517578
2015-05-30 17:31:54.118 Mjolnir[89886:13406834] -0.00013500452041625977
2015-05-30 17:31:54.118 Mjolnir[89886:13406834] -0.00012201070785522461
2015-05-30 17:31:54.118 Mjolnir[89886:13406834] -0.00027203559875488281
2015-05-30 17:31:54.119 Mjolnir[89886:13406834] -0.00024199485778808594
2015-05-30 17:31:54.119 Mjolnir[89886:13406834] -0.00014299154281616211
2015-05-30 17:31:54.119 Mjolnir[89886:13406834] -0.00011003017425537109
2015-05-30 17:31:54.119 Mjolnir[89886:13406834] -0.00010997056961059570
2015-05-30 17:31:54.120 Mjolnir[89886:13406834] -0.00026100873947143555
2015-05-30 17:31:54.120 Mjolnir[89886:13406834] -0.00023299455642700195
2015-05-30 17:31:54.120 Mjolnir[89886:13406834] -0.00013798475265502930
2015-05-30 17:31:54.121 Mjolnir[89886:13406834] -0.00058603286743164062
2015-05-30 17:31:54.121 Mjolnir[89886:13406834] -0.00013297796249389648
2015-05-30 17:31:54.122 Mjolnir[89886:13406834] -0.00011003017425537109
2015-05-30 17:31:54.122 Mjolnir[89886:13406834] -0.00029897689819335938
2015-05-30 17:31:54.123 Mjolnir[89886:13406834] -0.00033700466156005859
2015-05-30 17:31:54.123 Mjolnir[89886:13406834] -0.00040304660797119141
2015-05-30 17:31:54.123 Mjolnir[89886:13406834] -0.00018900632858276367
2015-05-30 17:31:54.132 Mjolnir[89886:13406834] -0.00844496488571166992

**Comment by nathankot** [comment]
@mbernath getting closer :)

`AXUIElementRef win` represents each window element  there is `AXUIElementGetPid` which should grab the pid for you documented here: https://developer.apple.com/library/mac/documentation/ApplicationServices/Reference/AXUIElement_header_reference/#//apple_ref/c/func/AXUIElementGetPid

Use like this:

```objc
pid_t pid;
AXUIElementGetPid(win, & pid);
```

**Comment by mbernath** [comment]
@nathankot Yes, got it! Thank you so much!

The program that causes the slowness is a component of a brother printer driver:

    /Library/Printers/Brother/Utilities/Server/NETserver.app/Contents/MacOS/NETserver 

Luckily I don't need that printer driver anymore... So I removed it. Now it's working just smoothly.

@skrobul Maybe you also want to run this benchmark without the "uncheck Displays have separate Spaces" workaround?! I wonder if it is the same printer driver or another app with your system...

**Comment by nathankot** [comment]
Nice! I wonder if we could automate this detection by packaging our own
`application` module
ᐧ

**Comment by nathankot** [comment]
Closing due to inactivity,
It's been solved for a select few but still no overall fix

**Comment by mattsawyer77** [comment]
I have seen this issue crop up every once in a while. Today I saw it again. I then opened my Activity Monitor and saw that my Adobe Cloud app was unresponsive. I killed that, and now it seems Mjolnir is snappy again. Oddly during this time, all my other running apps seemed to perform normally except for Mjolnir. I realize this may be specific to my system, but wanted to post this in case it helps anyone.
